export interface CareerGoal {
  id: string;
  slug: string;
  title: string;
  description: string;
  icon: string;
  category: "engineering" | "design" | "data" | "product" | "devops";
  requiredSkills: string[];
}

export const careerGoals: CareerGoal[] = [
  {
    id: "frontend-dev",
    slug: "frontend-developer",
    title: "Frontend Developer",
    description: "Build beautiful, responsive user interfaces and web apps",
    icon: "🎨",
    category: "engineering",
    requiredSkills: [
      "html",
      "css",
      "javascript",
      "typescript",
      "react",
      "nextjs",
      "tailwindcss",
      "git",
    ],
  },
  {
    id: "backend-dev",
    slug: "backend-developer",
    title: "Backend Developer",
    description: "Design APIs, databases, and server-side architecture",
    icon: "⚙️",
    category: "engineering",
    requiredSkills: [
      "nodejs",
      "python",
      "postgresql",
      "mongodb",
      "rest-api",
      "docker",
      "git",
      "linux",
    ],
  },
  {
    id: "fullstack-dev",
    slug: "fullstack-developer",
    title: "Full Stack Developer",
    description: "End-to-end application development from UI to database",
    icon: "🚀",
    category: "engineering",
    requiredSkills: [
      "html",
      "css",
      "javascript",
      "typescript",
      "react",
      "nodejs",
      "postgresql",
      "docker",
      "git",
    ],
  },
  {
    id: "mobile-dev",
    slug: "mobile-developer",
    title: "Mobile Developer",
    description: "Build native and cross-platform mobile applications",
    icon: "📱",
    category: "engineering",
    requiredSkills: [
      "react-native",
      "flutter",
      "swift",
      "kotlin",
      "typescript",
      "firebase",
      "git",
    ],
  },
  {
    id: "data-scientist",
    slug: "data-scientist",
    title: "Data Scientist",
    description: "Analyze data and build machine learning models",
    icon: "📊",
    category: "data",
    requiredSkills: [
      "python",
      "pandas",
      "numpy",
      "scikit-learn",
      "tensorflow",
      "sql",
      "statistics",
      "jupyter",
    ],
  },
  {
    id: "ml-engineer",
    slug: "ml-engineer",
    title: "ML Engineer",
    description: "Deploy and scale machine learning models in production",
    icon: "🤖",
    category: "data",
    requiredSkills: [
      "python",
      "tensorflow",
      "pytorch",
      "docker",
      "kubernetes",
      "mlops",
      "sql",
      "git",
    ],
  },
  {
    id: "devops-engineer",
    slug: "devops-engineer",
    title: "DevOps Engineer",
    description: "Automate infrastructure, CI/CD, and cloud deployments",
    icon: "☁️",
    category: "devops",
    requiredSkills: [
      "docker",
      "kubernetes",
      "aws",
      "terraform",
      "linux",
      "ci-cd",
      "python",
      "git",
    ],
  },
  {
    id: "ui-ux-designer",
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    description: "Design intuitive and visually stunning digital experiences",
    icon: "✨",
    category: "design",
    requiredSkills: [
      "figma",
      "prototyping",
      "user-research",
      "wireframing",
      "design-systems",
      "html",
      "css",
    ],
  },
];
